### ISSUE TITLE
Book sharing app user can Add , search , view, get, return book.

### ISSUE THREAD

**Issue by mauli-perennial** [mauli-perennial/BookCaseStudy#3]
Description:
This feature off book sharing app allow user to Add book, search book, view Book information.

Validations:
1) User can add book according to categories of book.
 
Other functional requirements:
1) User is able to see his activities when he choose to logout.

Acceptance criteria:
1) User can search book according to book name.
2) User can view book details in app.
3) can get Book from app and should able to see in his activities.

**Comment by udayraj-perennial** [comment]
Divide it in the following use cases:
Add - one or more copies
Search - by title, by author
Request - view the owner name and contact
Wait - when a book is not available
Return - Mark as returned when owner confirms
Get notifications - for book available and it's their turn in the waiting queue, a book is returned. Add all the notifications to a notification processing queue.
